version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pharmacy_service_postgres
    environment:
      POSTGRES_USER: pharmacyPostgres
      POSTGRES_PASSWORD: dRakyDKVyF5S
      POSTGRES_DB: pharmacyServicePostgresDatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:80"
    environment:
      SEQ_ACCEPT_EULA: Y
    volumes:
      - seq-data:/data
      - seq-logs:/logs

  consul:
    image: consul:latest
    container_name: dev-consul
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0

volumes:
  postgres-data:
  seq-data:
  seq-logs:
