using GroupAuthDefinitionService.Application.Features.GroupAuthDefinition.Rules.Abstractions;

namespace GroupAuthDefinitionService.Application.Features.GroupAuthDefinition.Rules;

public class GroupAuthDefinitionBusinessRule : IGroupAuthDefinitionBusinessRule
{
}